### PR TITLE
pushing schema.sql file to src/main/resources

### PR DESCRIPTION
**Pull request by GHPAUK**
# Description

Created a schema.sql file for films.

## Type of change

Please delete options that are not relevant.

- [* ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I have tested this in MYSQL workbench
image

# Checklist:

- [* ] My code follows the style guidelines of this project
- [* ] I have performed a self-review of my own code
- [* ] My changes generate no new warnings
- [* ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dhansak79** [comment]
Could you run this into a database and show that the sql functionally does what we want it to?

**Comment by GHPAUK** [comment]
> Could you run this into a database and show that the sql functionally does what we want it to?

Not just yet, this has the use of providing us all with the same schema - it will also be useful when we start integration testing the api - we will be able to utilise this file with the H2 database. However, while it does work as a sql statement it will likely need amending as we should probably include an PK ID field.

**Review by MustyC — CHANGES_REQUESTED** [review]
bad spelling

**Comment by GHPAUK** [comment]
> bad spelling

Fixed!! Please approve 🗡️

**Review by MustyC — APPROVED** [review]

**Pull request merged**
